#!/usr/bin/env bash
# Generate web/.env.local from Terraform output.
#
#   ./scripts/write-web-env.sh
#
# The file is gitignored and regenerated rather than edited. Every value in it
# changes when the estate is destroyed and recreated — the API id, the Cognito
# pool, the Hosted UI domain — so a committed copy would be wrong the first time
# somebody ran destroy, and wrong in a way that presents as a broken sign-in.

set -euo pipefail

ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../infra/terraform/envs/dev" && pwd)"
WEB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../web" && pwd)"
OUT="$WEB_DIR/.env.local"

get() { terraform -chdir="$ENV_DIR" output -raw "$1"; }

API_URL="$(get api_invoke_url)"

# The last path segment of the invoke URL is the API Gateway stage, and the client
# uses it as its request prefix so that CloudFront can route the path to the API
# unchanged. Derived rather than written twice: a prefix that disagrees with the
# stage produces a 404 from the site's own origin, which reads as a missing route.
API_PREFIX="/${API_URL##*/}"

{
  echo "# Generated by scripts/write-web-env.sh. Do not edit; do not commit."
  echo "# Regenerate after any terraform apply that changes the API or the pool."
  echo
  echo "VITE_API_URL=$API_URL"
  echo "VITE_API_PREFIX=$API_PREFIX"
  echo "VITE_COGNITO_HOSTED_UI=$(get cognito_hosted_ui_url)"
  echo "VITE_COGNITO_CLIENT_ID=$(get cognito_client_id)"
} > "$OUT"

# VITE_REDIRECT_URI is deliberately absent. auth.js falls back to
# window.location.origin, which is correct in both environments without a build
# flag: http://localhost:3000 when Vite serves it, the CloudFront domain when
# CloudFront does. Baking it in would make one build work in one place — and the
# build deployed to CloudFront would redirect sign-in to localhost.
#
# Both origins are registered in the user pool, so an unregistered one is refused
# by Cognito rather than silently accepted. That is the behaviour wanted.

printf '\033[36m==>\033[0m wrote %s\n' "$OUT"
grep -v '^#' "$OUT" | grep . | sed 's/^/    /'

cat <<'NOTE'

The redirect URI is not in this file: the client uses window.location.origin, so
one build works both locally and on CloudFront. Both origins must be registered as
callback URLs in the user pool, which Terraform does.

Vite runs with strictPort, so it cannot quietly move to 3001 and break the match
against the registered http://localhost:3000.
NOTE
