#!/usr/bin/env bash
# Generate web/.env.local from Terraform output.
#
#   ./scripts/write-web-env.sh
#
# The file is gitignored and regenerated rather than edited. Every value in it
# changes when the estate is destroyed and recreated — the API id, the Cognito
# pool, the Hosted UI domain — so a committed copy would be wrong the first time
# somebody ran destroy, and wrong in a way that presents as a broken sign-in.

set -euo pipefail

ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../infra/terraform/envs/dev" && pwd)"
WEB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../web" && pwd)"
OUT="$WEB_DIR/.env.local"

get() { terraform -chdir="$ENV_DIR" output -raw "$1"; }

{
  echo "# Generated by scripts/write-web-env.sh. Do not edit; do not commit."
  echo "# Regenerate after any terraform apply that changes the API or the pool."
  echo
  echo "VITE_API_URL=$(get api_invoke_url)"
  echo "VITE_COGNITO_HOSTED_UI=$(get cognito_hosted_ui_url)"
  echo "VITE_COGNITO_CLIENT_ID=$(get cognito_client_id)"
  echo "VITE_REDIRECT_URI=http://localhost:3000"
} > "$OUT"

printf '\033[36m==>\033[0m wrote %s\n' "$OUT"
grep -v '^#' "$OUT" | grep . | sed 's/^/    /'

cat <<'NOTE'

VITE_REDIRECT_URI must match a callback URL registered in the user pool exactly,
including the absence of a trailing slash. Vite is configured with strictPort so
it cannot quietly move to 3001 and break the match.
NOTE
